
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Martin Hara
 */
public class modul2soal2 extends javax.swing.JFrame {

    /**
     * Creates new form modul2soal2
     */
    public modul2soal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupmenu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu1 = new javax.swing.JRadioButton();
        menu2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        menu5 = new javax.swing.JRadioButton();
        menu6 = new javax.swing.JRadioButton();
        menu9 = new javax.swing.JRadioButton();
        menu10 = new javax.swing.JRadioButton();
        menu3 = new javax.swing.JRadioButton();
        menu7 = new javax.swing.JRadioButton();
        menu11 = new javax.swing.JRadioButton();
        menu4 = new javax.swing.JRadioButton();
        menu8 = new javax.swing.JRadioButton();
        menu12 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtangkabeli = new javax.swing.JLabel();
        btnbeli = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        hargasatuan = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu1.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroupmenu.add(menu1);
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("AYAM GULAI");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        jPanel2.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        buttonGroupmenu.add(menu2);
        menu2.setForeground(new java.awt.Color(255, 255, 255));
        menu2.setText("AYAM BAKAR");
        jPanel2.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PILIHAN MENU");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 30));

        buttonGroupmenu.add(menu5);
        menu5.setForeground(new java.awt.Color(255, 255, 255));
        menu5.setText("IKAN BAKAR");
        menu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu5ActionPerformed(evt);
            }
        });
        jPanel2.add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        buttonGroupmenu.add(menu6);
        menu6.setForeground(new java.awt.Color(255, 255, 255));
        menu6.setText("SAYUR NANGKA");
        jPanel2.add(menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        buttonGroupmenu.add(menu9);
        menu9.setForeground(new java.awt.Color(255, 255, 255));
        menu9.setText("GULAI SAYUR SINGKONG");
        menu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu9ActionPerformed(evt);
            }
        });
        jPanel2.add(menu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        buttonGroupmenu.add(menu10);
        menu10.setForeground(new java.awt.Color(255, 255, 255));
        menu10.setText("AYAM POP");
        jPanel2.add(menu10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        buttonGroupmenu.add(menu3);
        menu3.setForeground(new java.awt.Color(255, 255, 255));
        menu3.setText("AYAM GORENG");
        jPanel2.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        buttonGroupmenu.add(menu7);
        menu7.setForeground(new java.awt.Color(255, 255, 255));
        menu7.setText("TELOR ");
        menu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu7ActionPerformed(evt);
            }
        });
        jPanel2.add(menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        buttonGroupmenu.add(menu11);
        menu11.setForeground(new java.awt.Color(255, 255, 255));
        menu11.setText("GULAI KEPALA IKAN");
        jPanel2.add(menu11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        buttonGroupmenu.add(menu4);
        menu4.setForeground(new java.awt.Color(255, 255, 255));
        menu4.setText("BEBEK BAKAR");
        jPanel2.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        buttonGroupmenu.add(menu8);
        menu8.setForeground(new java.awt.Color(255, 255, 255));
        menu8.setText("RENDANG");
        jPanel2.add(menu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        buttonGroupmenu.add(menu12);
        menu12.setForeground(new java.awt.Color(255, 255, 255));
        menu12.setText("DENDENG");
        jPanel2.add(menu12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 570, 450));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setText("PAYAKUMBUAH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("MASAKAN PADANG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" JUMLAH BELI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, -1));

        txtangkabeli.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        txtangkabeli.setText(" 0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(txtangkabeli)
                .addGap(51, 51, 51))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtangkabeli)
                .addGap(24, 24, 24))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 120, 80));

        btnbeli.setText("BELI");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });
        jPanel3.add(btnbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        kurang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Minus_1.png")); // NOI18N
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel3.add(kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        tambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\Martin Hara\\Downloads\\Plus_1.png")); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel3.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFORMASI PESANAN");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PESANAN ANDA : ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("JUMLAH PESANAN :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("HARGA :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("TOTAL HARGA :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menu))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargasatuan))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(menu))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jumlah))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hargasatuan))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(total))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 170));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 280, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed
private int beli = 0; 
    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
         beli--;
    txtangkabeli.setText(String.valueOf(beli)); // Menetapkan nilai beli ke txtangkabeli
    if (beli <= 0) {
        kurang.setEnabled(false); // Menonaktifkan tombol jika kondisi terpenuhi
    }
    
    
    }//GEN-LAST:event_kurangActionPerformed

    private void menu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu7ActionPerformed

    private void menu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu9ActionPerformed

    private void menu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu5ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        // Increment nilai beli setiap kali tombol ditekan
    
    kurang.setEnabled(true); 
    beli++;
    
    txtangkabeli.setText(String.valueOf(beli)); // Menetapkan nilai beli ke txtangkabeli
    
    }//GEN-LAST:event_tambahActionPerformed

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
        // TODO add your handling code here:
        boolean itemDipilih = false;

        String selectedOptions = "";
        JLabel harga = new JLabel();
            if (menu1.isSelected()) {
                selectedOptions += "Ayam Gulai \n";
           harga.setText("15000");
itemDipilih = true;
            }
            if (menu2.isSelected()) {
                selectedOptions += "Ayam Bakar \n";
           harga.setText("15000");
 itemDipilih = true;
            }
            if (menu3.isSelected()) {
    selectedOptions += "Ayam Goreng \n";
    harga.setText("10000");
     itemDipilih = true;
}
if (menu4.isSelected()) {
    selectedOptions += "Bebek Bakar \n";
    harga.setText("18000");
     itemDipilih = true;
}
if (menu5.isSelected()) {
    selectedOptions += "Ikan Bakar \n";
    harga.setText("10000");
     itemDipilih = true;
}
if (menu6.isSelected()) {
    selectedOptions += "Sayur Nangka \n";
    harga.setText("12000");
     itemDipilih = true;
}
if (menu7.isSelected()) {
    selectedOptions += "Telor \n";
    harga.setText("8000");
     itemDipilih = true;
}
if (menu8.isSelected()) {
    selectedOptions += "Rendang \n";
    harga.setText("15000");
     itemDipilih = true;
}
if (menu9.isSelected()) {
    selectedOptions += "Gulai Sayur Singkong \n";
    harga.setText("5000");
     itemDipilih = true;
}
if (menu10.isSelected()) {
    selectedOptions += "Ayam Pop \n";
    harga.setText("13000");
     itemDipilih = true;
}
if (menu11.isSelected()) {
    selectedOptions += "Gulai Kepala Ikan \n";
    harga.setText("10000");
     itemDipilih = true;
}
if (menu12.isSelected()) {
    selectedOptions += "Dendeng \n";
    harga.setText("18000");
     itemDipilih = true;
}
 if (itemDipilih) {
        // Setel menu, jumlah, dan hargasatuan seperti yang Anda lakukan sebelumnya
        menu.setText(selectedOptions);
        jumlah.setText(String.valueOf(beli));
        hargasatuan.setText(String.valueOf(harga.getText()));

        total.setText(String.valueOf(Integer.parseInt(harga.getText()) * beli));
    } else {
        // Tampilkan peringatan jika tidak ada item yang dipilih
        JOptionPane.showMessageDialog(this, "Pilih setidaknya satu item terlebih dahulu.");
    }
    }//GEN-LAST:event_btnbeliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu.setText("");
        jumlah.setText("");
        hargasatuan.setText("");

        total.setText("");
        txtangkabeli.setText(" 0");
       
        menu1.setSelected(false);
        menu2.setSelected(false);
        menu3.setSelected(false);
        menu4.setSelected(false);
        menu5.setSelected(false);
        menu6.setSelected(false);
        menu7.setSelected(false);
        menu8.setSelected(false);
        menu9.setSelected(false);
        menu10.setSelected(false);
        menu11.setSelected(false);
        menu12.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modul2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modul2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modul2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modul2soal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modul2soal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.ButtonGroup buttonGroupmenu;
    private javax.swing.JLabel hargasatuan;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jumlah;
    private javax.swing.JButton kurang;
    private javax.swing.JLabel menu;
    private javax.swing.JRadioButton menu1;
    private javax.swing.JRadioButton menu10;
    private javax.swing.JRadioButton menu11;
    private javax.swing.JRadioButton menu12;
    private javax.swing.JRadioButton menu2;
    private javax.swing.JRadioButton menu3;
    private javax.swing.JRadioButton menu4;
    private javax.swing.JRadioButton menu5;
    private javax.swing.JRadioButton menu6;
    private javax.swing.JRadioButton menu7;
    private javax.swing.JRadioButton menu8;
    private javax.swing.JRadioButton menu9;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel total;
    private javax.swing.JLabel txtangkabeli;
    // End of variables declaration//GEN-END:variables
}
